name:                exceptiot
version:             0.0.1.0
github:              "parsonsmatt/exceptiot"
license:             BSD3
author:              "Matt Parsons"
maintainer:          parsonsmatt@gmail.com
copyright:           "2018 Matt Parsons"

extra-source-files:
- README.md
- changelog.md

# Metadata used when publishing your package
# synopsis:            make synopsis here
# category:            make category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/parsonsmatt/exceptiot#readme>

dependencies:
- base >= 4.7 && < 5
- unliftio
- mtl
- exceptions
- unliftio-core

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat

tests:
  exceptiot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - exceptiot
    - hspec
    build-tools:
    - hspec-discover
